using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Riddhasoft.EHajiriPro.Desktop.Migration
{
    internal sealed class Configuration : DbMigrationsConfiguration<Riddhasoft.DB.RiddhaDBContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
            ContextKey = "Riddhasoft.DB.RiddhaDBContext";
        }

        protected override void Seed(Riddhasoft.DB.RiddhaDBContext context)
        {

            // context.Menu.AddOrUpdate(x => x.Id,
            //             new EMenu() { Code = "0001", IsGroup = true, Name = "Set up", NameNp = "सेट अप", ParentCode = String.Empty, MenuIconCss = "fa fa-gears", MenuUrl = "#" },
            //             new EMenu() { Code = "1001", IsGroup = false, Name = "Fiscal Year", NameNp = "आर्थिक वर्ष", ParentCode = "0001", MenuIconCss = "fa  fa-calendar-o", MenuUrl = "/Office/FiscalYear" },
            //             new EMenu() { Code = "1002", IsGroup = false, Name = "Device", NameNp = "हाजिरी मेसिन्", ParentCode = "0001", MenuIconCss = "fa  fa-desktop", MenuUrl = "/Device/CompanyDevice" },
            //             new EMenu() { Code = "1003", IsGroup = false, Name = "Company Profile", NameNp = "कम्पनीको परिचय", ParentCode = "0001", MenuIconCss = "fa  fa-building-o", MenuUrl = "/Office/CompanyProfile" },
            //             new EMenu() { Code = "1004", IsGroup = false, Name = "Branch Management", NameNp = "शाखा ब्यवस्थापन ", ParentCode = "0001", MenuIconCss = "fa  fa-briefcase", MenuUrl = "/Office/Branch" },
            //             new EMenu() { Code = "1005", IsGroup = false, Name = "Department", NameNp = "विभाग", ParentCode = "0001", MenuIconCss = "fa  fa-gavel", MenuUrl = "/Office/Department" },
            //             new EMenu() { Code = "1006", IsGroup = false, Name = "Section", NameNp = "फाँट", ParentCode = "0001", MenuIconCss = "fa  fa-building", MenuUrl = "/Office/Section" },
            //             new EMenu() { Code = "1007", IsGroup = false, Name = "Designation", NameNp = "पद", ParentCode = "0001", MenuIconCss = "fa  fa-trophy", MenuUrl = "/Office/Designation" },
            //             new EMenu() { Code = "1008", IsGroup = false, Name = "Grade Group", NameNp = "दर्जा समुह", ParentCode = "0001", MenuIconCss = "fa  fa-columns", MenuUrl = "/Office/GradeGroup" },
            //             new EMenu() { Code = "1009", IsGroup = false, Name = "Shift", NameNp = "सिफ्ट", ParentCode = "0001", MenuIconCss = "fa  fa-clock-o", MenuUrl = "/Office/Shift" },
            //             new EMenu() { Code = "1010", IsGroup = false, Name = "Bank", NameNp = "बैंक", ParentCode = "0001", MenuIconCss = "fa  fa-dollar", MenuUrl = "/Office/Bank" },
            //             new EMenu() { Code = "0002", IsGroup = true, Name = "Office Management", NameNp = "कार्यलय ब्यवस्थापन", ParentCode = String.Empty, MenuIconCss = "fa  fa-building-o", MenuUrl = "#" },
            //             new EMenu() { Code = "2001", IsGroup = false, Name = "Employee", NameNp = "कर्मचारी", ParentCode = "0002", MenuIconCss = "fa  fa-user-md", MenuUrl = "/Employee/Employee" },
            //             new EMenu() { Code = "2002", IsGroup = false, Name = "Dynamic Roster", NameNp = "गतिशिल  कार्यसुची", ParentCode = "0002", MenuIconCss = "fa  fa-clock-o", MenuUrl = "/Employee/Roster" },
            //             new EMenu() { Code = "2003", IsGroup = false, Name = "Weekly Roster", NameNp = "साप्ताहिक कार्यसुची", ParentCode = "0002", MenuIconCss = "fa  fa-clock-o", MenuUrl = "/Employee/WeeklyRoster" },
            //             new EMenu() { Code = "2004", IsGroup = false, Name = "Holiday", NameNp = "सार्वजनिक बिदा", ParentCode = "0002", MenuIconCss = "fa  fa-television", MenuUrl = "/Office/Holiday" },
            //             new EMenu() { Code = "2005", IsGroup = false, Name = "Manual Punch", NameNp = "हाजिरी", ParentCode = "0002", MenuIconCss = "fa fa-thumbs-up", MenuUrl = "/Employee/ManualPunch" },
            //             new EMenu() { Code = "2006", IsGroup = false, Name = "Notice", NameNp = "सूचना", ParentCode = "0002", MenuIconCss = "fa fa-newspaper-o", MenuUrl = "/Employee/Notice" },
            //             new EMenu() { Code = "2007", IsGroup = false, Name = "Event", NameNp = "इभेन्ट", ParentCode = "0002", MenuIconCss = "fa fa-calendar", MenuUrl = "/Employee/Event" },
            //             new EMenu() { Code = "2008", IsGroup = false, Name = "Office Visit", NameNp = "कार्यलय भ्रमन", ParentCode = "0002", MenuIconCss = "fa  fa-bookmark", MenuUrl = "/Employee/OfficeVisit" },
            //             new EMenu() { Code = "0003", IsGroup = true, Name = "Leave Management", NameNp = "बिदा ब्यवस्थापन", ParentCode = String.Empty, MenuIconCss = "fa  fa-bed", MenuUrl = "#" },
            //             new EMenu() { Code = "3001", IsGroup = false, Name = "Leave Master", NameNp = "बिदा", ParentCode = "0003", MenuIconCss = "fa  fa-home", MenuUrl = "/Office/LeaveMaster" },
            //             new EMenu() { Code = "3002", IsGroup = false, Name = "Leave Application", NameNp = "बिदाको लागी निवेदन", ParentCode = "0003", MenuIconCss = "fa  fa-paperclip", MenuUrl = "/Employee/LeaveApplication" },
            //             new EMenu() { Code = "3003", IsGroup = false, Name = "Leave Approval", NameNp = "बिदाको लागी स्विकृती", ParentCode = "0003", MenuIconCss = "fa  fa-check", MenuUrl = "/Employee/LeaveApproval" },
            //             new EMenu() { Code = "3004", IsGroup = false, Name = "Leave Settlement", NameNp = "बिदा मीलाउने", ParentCode = "0003", MenuIconCss = "fa  fa-file-o", MenuUrl = "/Employee/LeaveSettlement" },
            //             new EMenu() { Code = "3005", IsGroup = false, Name = "Leave Quota", NameNp = "बिदा कोटा", ParentCode = "0003", MenuIconCss = "fa  fa-trophy", MenuUrl = "/Office/Designation" },
            //             new EMenu() { Code = "0004", IsGroup = true, Name = "User Management", NameNp = "प्रयोगकर्ता ब्यवस्थापन", ParentCode = String.Empty, MenuIconCss = "fa  fa-user-circle", MenuUrl = "#" },
            //             new EMenu() { Code = "4001", IsGroup = false, Name = "User Group/Role", NameNp = "प्रयोगकर्ताको समुह/भूमिका", ParentCode = "0004", MenuIconCss = "fa  fa-user-plus", MenuUrl = "/User/UserRole" },
            //             new EMenu() { Code = "4002", IsGroup = false, Name = "User", NameNp = "प्रयोगकर्ता", ParentCode = "0004", MenuIconCss = "fa  fa-user", MenuUrl = "/User/User" },
            //             new EMenu() { Code = "0005", IsGroup = true, Name = "Report", NameNp = "प्रतिवेदन", ParentCode = String.Empty, MenuIconCss = "fa  fa-pie-chart", MenuUrl = "#" },
            //             new EMenu() { Code = "5001", IsGroup = false, Name = "Attendance Report", NameNp = "हाजिरी प्रतिवेदन", ParentCode = "0005", MenuIconCss = "fa  fa-book", MenuUrl = "/Report/AttendanceReport" },
            //             new EMenu() { Code = "0006", IsGroup = true, Name = "Dashboard Widgets", NameNp = "ड्यास्बोर्ड विजेट", ParentCode = String.Empty, MenuIconCss = String.Empty, MenuUrl = String.Empty, IsWidget = true },
            //             new EMenu() { Code = "0007", IsGroup = true, Name = "HR Management", NameNp = "मानव स्रोत व्यवस्थापन", ParentCode = String.Empty, MenuIconCss = "fa fa-male", MenuUrl = "#", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "7001", IsGroup = false, Name = "Employee", NameNp = "कर्मचारी", ParentCode = "0007", MenuIconCss = "fa fa-user-md", MenuUrl = "/HRM/Contract", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "7002", IsGroup = false, Name = "Employee Status Verification", NameNp = "कर्मचारी स्थिति प्रमाणिकरण", ParentCode = "0007", MenuIconCss = "fa fa-sitemap", MenuUrl = "/HRM/verification", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "7004", IsGroup = false, Name = "Employment Status", NameNp = "रोजगार स्थिति", ParentCode = "0007", MenuIconCss = "fa fa-columns", MenuUrl = "/HRM/employmentStatus", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "7005", IsGroup = false, Name = "Education", NameNp = "शिक्षा", ParentCode = "0007", MenuIconCss = "fa fa-book", MenuUrl = "/HRM/Education", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "7006", IsGroup = false, Name = "Language", NameNp = "भाषा", ParentCode = "0007", MenuIconCss = "fa fa-pencil", MenuUrl = "/HRM/Language", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "7007", IsGroup = false, Name = "License", NameNp = "लाइसेन्स", ParentCode = "0007", MenuIconCss = "fa fa-id-card", MenuUrl = "/HRM/License", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "7008", IsGroup = false, Name = "Skills", NameNp = "कौशल", ParentCode = "0007", MenuIconCss = "fa fa-briefcase", MenuUrl = "/HRM/Skills", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "0008", IsGroup = true, Name = "Payroll Management", NameNp = "तलबी बिबरण व्यवस्थापन", ParentCode = String.Empty, MenuIconCss = "fa fa-usd", MenuUrl = "#", SoftwarePackageType = 2 },
            //             new EMenu() { Code = "8001", IsGroup = false, Name = "Allowance", NameNp = "भत्ता", ParentCode = "0008", MenuIconCss = "fa fa-plus", MenuUrl = "/Payroll/Allowance", SoftwarePackageType = 2 },
            //             new EMenu() { Code = "8002", IsGroup = false, Name = "Deduction", NameNp = "कटौती ", ParentCode = "0008", MenuIconCss = "fa fa-minus", MenuUrl = "/Payroll/Deduction", SoftwarePackageType = 2 },
            //             new EMenu() { Code = "8003", IsGroup = false, Name = "Payroll Setup", NameNp = "तलबी बिबरण ", ParentCode = "0008", MenuIconCss = "fa fa-credit-card", MenuUrl = "/Payroll/Payroll", SoftwarePackageType = 2 },
            //             new EMenu() { Code = "8004", IsGroup = false, Name = "Fixed Roster", NameNp = "स्थिर कार्यसुची", ParentCode = "0002", MenuIconCss = "fa  fa-clock-o", MenuUrl = "/Employee/FixedRoster" },
            //             new EMenu() { Code = "8005", IsGroup = false, Name = "Payroll Verification", NameNp = "तलबी प्रमाणिकरण ", ParentCode = "0008", MenuIconCss = "fa fa-sitemap", MenuUrl = "/Payroll/PayrollVerification", SoftwarePackageType = 2 },
            //             new EMenu() { Code = "8006", IsGroup = false, Name = "Course", NameNp = "पाठ्यक्रम", ParentCode = "0007", MenuIconCss = "fa fa-book", MenuUrl = "/HRM/Course", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8007", IsGroup = false, Name = "session", NameNp = "सत्र", ParentCode = "0007", MenuIconCss = "fa fa-bookmark", MenuUrl = "/HRM/Session", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8008", IsGroup = false, Name = "Participating Session", NameNp = "सहभागी सत्र", ParentCode = "0007", MenuIconCss = "fa fa-database", MenuUrl = "/HRM/Participant", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8009", IsGroup = false, Name = "Leave Report", NameNp = "बिदा प्रतिवेदन", ParentCode = "0005", MenuIconCss = "fa  fa-book", MenuUrl = "/Report/LeaveReport" },
            //             new EMenu() { Code = "8011", IsGroup = false, Name = "Travel", NameNp = "यात्रा", ParentCode = "0007", MenuIconCss = "fa fa-plane", MenuUrl = "/HRM/TravelRequest", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8010", IsGroup = false, Name = "Custom Field", NameNp = "अनुकूलन क्षेत्र", ParentCode = "0007", MenuIconCss = "fa fa-plus-square", MenuUrl = "/HRM/CustomField", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8012", IsGroup = false, Name = "Disciplinary Cases", NameNp = "शास्त्रीय मामला", ParentCode = "0007", MenuIconCss = "fa fa-university", MenuUrl = "/HRM/DisciplinaryCases", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8013", IsGroup = false, Name = "HR Report", NameNp = "मानव स्रोत प्रतिवेदन", ParentCode = "0005", MenuIconCss = "fa fa-male", MenuUrl = "/Report/HrReport", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8014", IsGroup = false, Name = "Travel Ticket", NameNp = "यात्रा टिकट", ParentCode = "0007", MenuIconCss = "fa fa-plane", MenuUrl = "/HRM/FOC", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8015", IsGroup = false, Name = "Travel Ticket Approval", NameNp = "यात्रा टिकटको अनुमोदन", ParentCode = "0007", MenuIconCss = "fa fa-check", MenuUrl = "/HRM/FOCApproval", SoftwarePackageType = 1 },
            //             new EMenu() { Code = "8016", IsGroup = false, Name = "Leave Replacement", NameNp = "बिदाको प्रतिस्थापन", ParentCode = "0003", MenuIconCss = "fa fa-arrows-h", MenuUrl = "/Employee/ApproveReplacementLeave" },
            //             new EMenu() { Code = "8017", IsGroup = false, Name = "Payroll Configuration", NameNp = "तलबी विवरण कन्फिगरेसन", ParentCode = "0008", MenuIconCss = "fa fa-cog", MenuUrl = "/PayRoll/PayrollConfiguration", SoftwarePackageType = 2 },
            //             //new
            //             new EMenu() { Code = "8018", IsGroup = false, Name = "Payroll Report", NameNp = "तलबी प्रतिवेदन", ParentCode = "0005", MenuIconCss = "fa  fa-money", MenuUrl = "/Report/PayRollReport", SoftwarePackageType = 2 },
            //             new EMenu() { Code = "8019", IsGroup = false, Name = "Office Visit Approval", NameNp = "कार्यलय भ्रमन स्विकृती", ParentCode = "0002", MenuIconCss = "fa  fa-check", MenuUrl = "/Employee/OfficeVisitApproval" },
            //             new EMenu() { Code = "8020", IsGroup = false, Name = "Kaj", NameNp = "काज", ParentCode = "0002", MenuIconCss = "fa  fa-bookmark", MenuUrl = "/Employee/Kaj" },
            //             new EMenu() { Code = "8021", IsGroup = false, Name = "Kaj Approval", NameNp = "काज स्विकृती", ParentCode = "0002", MenuIconCss = "fa  fa-check", MenuUrl = "/Employee/KajApproval" },
            //             new EMenu() { Code = "8022", IsGroup = false, Name = "Tax Setup", NameNp = "कर सेटअप", ParentCode = "0008", MenuIconCss = "fa  fa-money", MenuUrl = "/PayRoll/TaxSetup", SoftwarePackageType = 3 },

            ////               /*8023 is already assign to Leave Opening Balance*/
            //               new EMenu() { Code = "8025", IsGroup = false, Name = "Insurance Company", NameNp = "बीमा कम्पनी", ParentCode = "0008", MenuIconCss = "fa  fa-building-o", MenuUrl = "/PayRoll/InsuranceCompany", SoftwarePackageType = 3 },
            //               new EMenu() { Code = "8026", IsGroup = false, Name = "Reporting Lineup", NameNp = "रिपोर्टिंग लाइनअप", ParentCode = "0007", MenuIconCss = "fa  fa-book", MenuUrl = "/HRM/ReportingLineUp", SoftwarePackageType = 3 },
            //               new EMenu() { Code = "8024", IsGroup = false, Name = "Salary Sheet", NameNp = "तलब सिट", ParentCode = "0008", MenuIconCss = "fa  fa-book", MenuUrl = "/PayRoll/SalarySheet", SoftwarePackageType = 3 },
            //               new EMenu() { Code = "8027", IsGroup = false, Name = "Salary Payment", NameNp = "तलब भुक्तानी", ParentCode = "0008", MenuIconCss = "fa  fa-book", MenuUrl = "/PayRoll/SalaryPayment", SoftwarePackageType = 3 },
            //               new EMenu() { Code = "8028", IsGroup = false, Name = "Salary Payslip", NameNp = "तलब भुक्तान पर्ची", ParentCode = "0008", MenuIconCss = "fa  fa-book", MenuUrl = "/PayRoll/SalaryApproval", SoftwarePackageType = 3 },
            //               new EMenu() { Code = "8029", IsGroup = false, Name = "Salary Approval", NameNp = "तलब स्वीकृति", ParentCode = "0008", MenuIconCss = "fa  fa-book", MenuUrl = "/PayRoll/SalaryApproval", SoftwarePackageType = 3 },


            // new EMenu() { Code = "8030", IsGroup = false, Name = "ManualPunch Request", NameNp = "हाजिरी अनुरोध", ParentCode = "0002", MenuIconCss = "fa fa-thumbs-up", MenuUrl = "/Employee/ManualPunchRequest" }
            // new EMenu() { Code = "8031", IsGroup = false, Name = "Office Visit Request", NameNp = "Office Visit Request", ParentCode = "0002", MenuIconCss = "fa fa-thumbs-up", MenuUrl = "/Employee/OfficeVisitRequest" }


            //);

            //context.MenuAction.AddOrUpdate(x => x.Id,
            //                                         new EMenuAction() { MenuCode = "1001", ActionCode = "1038", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1001", ActionCode = "1011", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1001", ActionCode = "1012", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1001", ActionCode = "1013", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "1002", ActionCode = "1039", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1002", ActionCode = "1014", Desc = "Update" },
            //                                         new EMenuAction() { MenuCode = "1003", ActionCode = "1040", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1003", ActionCode = "1015", Desc = "Update" },
            //                                         new EMenuAction() { MenuCode = "1004", ActionCode = "1041", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1004", ActionCode = "1016", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1004", ActionCode = "1017", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1004", ActionCode = "1018", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "1005", ActionCode = "1042", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1005", ActionCode = "1019", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1005", ActionCode = "1020", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1005", ActionCode = "1021", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "1006", ActionCode = "1043", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1006", ActionCode = "1022", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1006", ActionCode = "1023", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1006", ActionCode = "1024", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "1007", ActionCode = "1044", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1007", ActionCode = "1025", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1007", ActionCode = "1026", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1007", ActionCode = "1027", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "1007", ActionCode = "1028", Desc = "Leave Quota" },
            //                                         new EMenuAction() { MenuCode = "1008", ActionCode = "1045", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1008", ActionCode = "1029", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1008", ActionCode = "1030", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1008", ActionCode = "1031", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "1009", ActionCode = "1046", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1009", ActionCode = "1032", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1009", ActionCode = "1033", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1009", ActionCode = "1034", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "1010", ActionCode = "1047", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "1010", ActionCode = "1035", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "1010", ActionCode = "1036", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "1010", ActionCode = "1037", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2036", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2009", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2010", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2011", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2012", Desc = "View Details" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2013", Desc = "Pull Device Employee" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2014", Desc = "Login" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2015", Desc = "Download Excel Format" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2016", Desc = "Export" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2017", Desc = "Upload Excel File" },
            //                                         new EMenuAction() { MenuCode = "2001", ActionCode = "2044", Desc = "Shift Type" },
            //                                         new EMenuAction() { MenuCode = "2002", ActionCode = "2037", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2002", ActionCode = "2018", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2002", ActionCode = "2045", Desc = "Export Roster" },
            //                                         new EMenuAction() { MenuCode = "2002", ActionCode = "2046", Desc = "Upload Roster" },
            //                                         new EMenuAction() { MenuCode = "2003", ActionCode = "2038", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2003", ActionCode = "2019", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2004", ActionCode = "2039", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2004", ActionCode = "2020", Desc = "Pull Default Holiday" },
            //                                         new EMenuAction() { MenuCode = "2004", ActionCode = "2021", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2004", ActionCode = "2022", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "2004", ActionCode = "2023", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "2005", ActionCode = "2040", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2005", ActionCode = "2024", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2005", ActionCode = "2025", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "2005", ActionCode = "2026", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "2006", ActionCode = "2041", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2006", ActionCode = "2027", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2006", ActionCode = "2028", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "2006", ActionCode = "2029", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "2007", ActionCode = "2042", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2007", ActionCode = "2030", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2007", ActionCode = "2031", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "2007", ActionCode = "2032", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "2008", ActionCode = "2043", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "2008", ActionCode = "2033", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "2008", ActionCode = "2034", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "2008", ActionCode = "2035", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "3001", ActionCode = "3025", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "3001", ActionCode = "3006", Desc = "Pull Default Leave" },
            //                                         new EMenuAction() { MenuCode = "3001", ActionCode = "3007", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "3001", ActionCode = "3008", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "3001", ActionCode = "3009", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "3002", ActionCode = "3026", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "3002", ActionCode = "3010", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "3002", ActionCode = "3011", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "3002", ActionCode = "3012", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "3003", ActionCode = "3027", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "3003", ActionCode = "3013", Desc = "Approve" },
            //                                         new EMenuAction() { MenuCode = "3003", ActionCode = "3014", Desc = "Reject" },
            //                                         new EMenuAction() { MenuCode = "3004", ActionCode = "3028", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "3004", ActionCode = "3018", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "3004", ActionCode = "3019", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "3004", ActionCode = "3020", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "3005", ActionCode = "3029", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "3005", ActionCode = "3021", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "3005", ActionCode = "3022", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "3005", ActionCode = "3023", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "3005", ActionCode = "3024", Desc = "Leave Quota" },
            //                                         new EMenuAction() { MenuCode = "4001", ActionCode = "4009", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "4001", ActionCode = "4003", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "4001", ActionCode = "4004", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "4001", ActionCode = "4005", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "4001", ActionCode = "4010", Desc = "Permission" },
            //                                         new EMenuAction() { MenuCode = "4002", ActionCode = "4011", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "4002", ActionCode = "4006", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "4002", ActionCode = "4007", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "4002", ActionCode = "4008", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5011", Desc = "Daily EmployeeAttendance Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5002", Desc = "DailyEarlyInReport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5003", Desc = "DailyEarlyOutReport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5004", Desc = "DailyEmployeeAbsentReport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5005", Desc = "DailyLateInReport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5006", Desc = "DailyLateOutReport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5007", Desc = "DailyMissingPunchesReport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5008", Desc = "MonthlyAttendancereport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5009", Desc = "MonthlyEmployeeSummaryReport" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "5010", Desc = "DailyEmployeeLeaveReport" },
            //                                         new EMenuAction() { MenuCode = "0006", ActionCode = "6001", Desc = "Attendance Info" },
            //                                         new EMenuAction() { MenuCode = "0006", ActionCode = "6002", Desc = "Calender" },
            //                                         new EMenuAction() { MenuCode = "0006", ActionCode = "6003", Desc = "News" },
            //                                         new EMenuAction() { MenuCode = "0006", ActionCode = "6004", Desc = "self Attendance Summary" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7100", Desc = "Contract View" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7101", Desc = "Contract Create" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7102", Desc = "Contract Edit" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7103", Desc = "Contract Delete" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7104", Desc = "Resignation View" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7105", Desc = "Resignation Create" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7106", Desc = "Termination View" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7107", Desc = "Termination Create" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7108", Desc = "Contract Verification" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7109", Desc = "Contract View" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7110", Desc = "Contract Approval" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7111", Desc = "Termination Verification" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7112", Desc = "Termination View" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7113", Desc = "Termination Approval" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7114", Desc = "Resignation Verification" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7115", Desc = "Resignation View" },
            //                                         new EMenuAction() { MenuCode = "7002", ActionCode = "7116", Desc = "Resignation Approval" },
            //                                         new EMenuAction() { MenuCode = "7004", ActionCode = "7117", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "7004", ActionCode = "7118", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "7004", ActionCode = "7119", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "7004", ActionCode = "7120", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "7001", ActionCode = "7121", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8004", ActionCode = "7122", Desc = "RefreshRoster" },
            //                                         new EMenuAction() { MenuCode = "8004", ActionCode = "7123", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7124", Desc = "Monthly Attendance Statistic Report" },
            //                                         new EMenuAction() { MenuCode = "8006", ActionCode = "7125", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8006", ActionCode = "7126", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8006", ActionCode = "7127", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8006", ActionCode = "7128", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8007", ActionCode = "7129", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8007", ActionCode = "7130", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8007", ActionCode = "7131", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8007", ActionCode = "7132", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8008", ActionCode = "7133", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8008", ActionCode = "7134", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8008", ActionCode = "7135", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8008", ActionCode = "7136", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "7005", ActionCode = "7137", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "7005", ActionCode = "7138", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "7005", ActionCode = "7139", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "7005", ActionCode = "7140", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "7006", ActionCode = "7141", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "7006", ActionCode = "7142", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "7006", ActionCode = "7143", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "7006", ActionCode = "7144", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "7007", ActionCode = "7145", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "7007", ActionCode = "7146", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "7007", ActionCode = "7147", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "7007", ActionCode = "7148", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "7008", ActionCode = "7149", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "7008", ActionCode = "7150", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "7008", ActionCode = "7151", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "7008", ActionCode = "7152", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8009", ActionCode = "7153", Desc = "Employee Wise Leave Report" },
            //                                         new EMenuAction() { MenuCode = "8009", ActionCode = "7154", Desc = "Leave Wise Leave Report" },
            //                                         new EMenuAction() { MenuCode = "8010", ActionCode = "7155", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8010", ActionCode = "7156", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8010", ActionCode = "7157", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8010", ActionCode = "7158", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8011", ActionCode = "7159", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8011", ActionCode = "7160", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8011", ActionCode = "7161", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8011", ActionCode = "7162", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8012", ActionCode = "7163", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8012", ActionCode = "7164", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8012", ActionCode = "7165", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8012", ActionCode = "7166", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7167", Desc = "Contract Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7168", Desc = "Termination Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7169", Desc = "Resignation Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7170", Desc = "Employee Details Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7171", Desc = "Monthly Early In Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7172", Desc = "Monthly Early Out Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7173", Desc = "Monthly Late In Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7174", Desc = "Monthly Late Out Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7175", Desc = "Monthly Absent Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7176", Desc = "Monthly Missing Punches Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7177", Desc = "Monthly Leave Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7178", Desc = "Monthly Roster Report" },
            //                                         new EMenuAction() { MenuCode = "8014", ActionCode = "7179", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8014", ActionCode = "7180", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8014", ActionCode = "7181", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8014", ActionCode = "7182", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7183", Desc = "Experience Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7184", Desc = "Qualification Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7185", Desc = "Course Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7186", Desc = "Session Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7187", Desc = "Participant Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7188", Desc = "Disciplinary Case Wise Report" },
            //                                         new EMenuAction() { MenuCode = "8013", ActionCode = "7189", Desc = "Disciplinary Employee Wise Report" },
            //                                         new EMenuAction() { MenuCode = "8015", ActionCode = "7190", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8015", ActionCode = "7191", Desc = "Approval" },
            //                                         new EMenuAction() { MenuCode = "8015", ActionCode = "7192", Desc = "Revert" },
            //                                         new EMenuAction() { MenuCode = "8015", ActionCode = "7193", Desc = "Details" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7194", Desc = "Ot Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7195", Desc = "Ot Claim Report" },
            //                                         new EMenuAction() { MenuCode = "8016", ActionCode = "7196", Desc = "view" },
            //                                         new EMenuAction() { MenuCode = "8016", ActionCode = "7197", Desc = "refresh" },
            //                                         new EMenuAction() { MenuCode = "8016", ActionCode = "7198", Desc = "approve" },
            //                                         new EMenuAction() { MenuCode = "8016", ActionCode = "7201", Desc = "Approval List" },
            //                                         new EMenuAction() { MenuCode = "8017", ActionCode = "7199", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8017", ActionCode = "7200", Desc = "Create/Update" },
            //                                         new EMenuAction() { MenuCode = "8001", ActionCode = "7220", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8001", ActionCode = "7202", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8001", ActionCode = "7203", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8001", ActionCode = "7204", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8002", ActionCode = "7205", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8002", ActionCode = "7206", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8002", ActionCode = "7207", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8002", ActionCode = "7208", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8003", ActionCode = "7209", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8003", ActionCode = "7210", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8003", ActionCode = "7211", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8003", ActionCode = "7212", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8003", ActionCode = "7217", Desc = "Grade Upgrade" },
            //                                         new EMenuAction() { MenuCode = "8005", ActionCode = "7213", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8005", ActionCode = "7214", Desc = "Approval" },
            //                                         new EMenuAction() { MenuCode = "8005", ActionCode = "7215", Desc = "Revert" },
            //                                         new EMenuAction() { MenuCode = "8005", ActionCode = "7216", Desc = "Details" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7218", Desc = "Daily Manual Punch Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7219", Desc = "Monthly Manual Punch Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7220", Desc = "Daily Office Visit Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7221", Desc = "Monthly Office Visit Report" },
            //                                         new EMenuAction() { MenuCode = "5001", ActionCode = "7222", Desc = "Daily Employee Ot Report" },

            //                                         // new  Action
            //                                         new EMenuAction() { MenuCode = "8018", ActionCode = "7223", Desc = "Employee Payroll Summary Report" },
            //                                         new EMenuAction() { MenuCode = "8018", ActionCode = "7224", Desc = "Employee Allownace Report" },
            //                                         new EMenuAction() { MenuCode = "8019", ActionCode = "7225", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8019", ActionCode = "7226", Desc = "Approval" },
            //                                         new EMenuAction() { MenuCode = "8020", ActionCode = "7227", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8020", ActionCode = "7228", Desc = "Create" },
            //                                         new EMenuAction() { MenuCode = "8020", ActionCode = "7229", Desc = "Edit" },
            //                                         new EMenuAction() { MenuCode = "8020", ActionCode = "7230", Desc = "Delete" },
            //                                         new EMenuAction() { MenuCode = "8021", ActionCode = "7231", Desc = "View" },
            //                                         new EMenuAction() { MenuCode = "8021", ActionCode = "7232", Desc = "Approval" },

            //                                           //    Added by Raz 2019-08-30
            //                                           /*Tax Setup*/
            //                                           new EMenuAction() { MenuCode = "8022", ActionCode = "7233", Desc = "View" },
            //                                           new EMenuAction() { MenuCode = "8022", ActionCode = "7234", Desc = "Create" },
            //                                           new EMenuAction() { MenuCode = "8022", ActionCode = "7235", Desc = "Edit" },
            //                                           new EMenuAction() { MenuCode = "8022", ActionCode = "7236", Desc = "Delete" },
            //                                           new EMenuAction() { MenuCode = "8022", ActionCode = "7237", Desc = "View Details" },

            //                                           /*Insurance Company*/
            //                                           new EMenuAction() { MenuCode = "8025", ActionCode = "7238", Desc = "View" },
            //                                           new EMenuAction() { MenuCode = "8025", ActionCode = "7239", Desc = "Create" },
            //                                           new EMenuAction() { MenuCode = "8025", ActionCode = "7240", Desc = "Edit" },
            //                                           new EMenuAction() { MenuCode = "8025", ActionCode = "7241", Desc = "Delete" },

            //                                           /*Salary Sheet*/
            //                                           new EMenuAction() { MenuCode = "8024", ActionCode = "7242", Desc = "View" },
            //                                           new EMenuAction() { MenuCode = "8024", ActionCode = "7243", Desc = "Create" },
            //                                           new EMenuAction() { MenuCode = "8024", ActionCode = "7244", Desc = "Edit" },
            //                                           new EMenuAction() { MenuCode = "8024", ActionCode = "7245", Desc = "Delete" },

            //                                            /*Pay Roll*/
            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7246", Desc = "Advance Salary View" },
            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7247", Desc = "Create Advance Salary" },
            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7248", Desc = "Edit Advance Salary" },
            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7249", Desc = "Delete Advance Salary" },

            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7250", Desc = "Insurance Salary View" },
            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7251", Desc = "Create Insurance Salary" },
            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7252", Desc = "Edit Insurance Salary" },
            //                                            new EMenuAction() { MenuCode = "8003", ActionCode = "7253", Desc = "Delete Insurance Salary" },

            //                                            /*Reporting Lineup*/
            //                                            new EMenuAction() { MenuCode = "8026", ActionCode = "7254", Desc = "View" },
            //                                            new EMenuAction() { MenuCode = "8026", ActionCode = "7255", Desc = "Create" },
            //                                            new EMenuAction() { MenuCode = "8026", ActionCode = "7256", Desc = "Edit" },
            //                                            new EMenuAction() { MenuCode = "8026", ActionCode = "7257", Desc = "Delete" },


            //                                            /*Salary Payment*/
            //                                            new EMenuAction() { MenuCode = "8027", ActionCode = "7258", Desc = "View" },
            //                                            new EMenuAction() { MenuCode = "8027", ActionCode = "7259", Desc = "Create" },


            //                                            /*Salary Payslip*/
            //                                            new EMenuAction() { MenuCode = "8028", ActionCode = "7260", Desc = "View" },
            //                                            new EMenuAction() { MenuCode = "8028", ActionCode = "7261", Desc = "Generate Payslip" },

            //                                            /*Salary Approval*/
            //                                            new EMenuAction() { MenuCode = "8029", ActionCode = "7262", Desc = "View" },
            //                                            new EMenuAction() { MenuCode = "8029", ActionCode = "7263", Desc = "Approval" },
            //                                            new EMenuAction() { MenuCode = "8029", ActionCode = "7264", Desc = "Review" },

            /*Manual Punch Request*/
            //new EMenuAction() { MenuCode = "8030", ActionCode = "7265", Desc = "View" },
            //new EMenuAction() { MenuCode = "8030", ActionCode = "7266", Desc = "View Detail" },
            //new EMenuAction() { MenuCode = "8030", ActionCode = "7267", Desc = "Approval" },
            //new EMenuAction() { MenuCode = "8030", ActionCode = "7268", Desc = "Delete" }

            /*Office Visit Request*/
            //new EMenuAction() { MenuCode = "8031", ActionCode = "7269", Desc = "View" },
            //new EMenuAction() { MenuCode = "8031", ActionCode = "7270", Desc = "View Detail" },
            //new EMenuAction() { MenuCode = "8031", ActionCode = "7271", Desc = "Approval" },
            //new EMenuAction() { MenuCode = "8031", ActionCode = "7272", Desc = "Delete" }
            // );
        }
    }
}
