ALTER PROC SP_GET_NOTIFICATION_BY_EMP_ID
(
 @EMPLOYEE_ID INT=3,
 @FROMDATE DATETIME='2017-09-16',
 @TODATE DATETIME='2017-10-16')
 AS BEGIN
 --NOTIFICATION LEVEL 1=>BRANCH ,2=>DEPARTMENT,3=>SECTION,4=>EMPLOYEE
 DECLARE @SECTIONID INT=0;
 DECLARE @DEPARTMENTID INT=0;
 DECLARE @BRANCH_ID INT=0;
 SELECT @SECTIONID=ES.Id, @DEPARTMENTID=ED.Id,@BRANCH_ID=EM.BranchId FROM EEmployees EM
	INNER JOIN	ESections ES ON ES.Id = EM.SectionId
	INNER JOIN EDepartments ED ON ED.Id= ES.DepartmentId
	INNER JOIN EBranches EB ON EB.Id=ES.BranchId 
	WHERE EM.Id=@EMPLOYEE_ID
  
	SELECT DISTINCT Title,[Message] ,ED.NepDate [Date],Convert(varchar(5),TypeId) Type,(case when TargetId is null then 0 else TargetId end) targetid,DATEDIFF(D,@FROMDATE,EffectiveDate) RemDays,PublishDate FROM ENOTIFICATIONS NM
		LEFT JOIN ENOTIFICATIONDETAILS ND ON ND.NOTIFICATIONID=NM.ID
		inner join EDateTables ED ON ED.EngDate=EffectiveDate
	WHERE (( cONVERT(DATE,PublishDate)>=@FROMDATE AND cONVERT(DATE,PublishDate)<= @TODATE )or( cONVERT(DATE,ExpiryDate)>=@FROMDATE AND cONVERT(DATE,ExpiryDate)<= @TODATE )) AND COMPANYID=@BRANCH_ID
	AND 
	(((CASE WHEN NotificationLevel=0 THEN NULL 
	 WHEN NotificationLevel=1 THEN @BRANCH_ID 
	 WHEN NotificationLevel=2 THEN @DEPARTMENTID
	 WHEN NotificationLevel=3 THEN @SECTIONID
	 ELSE  @EMPLOYEE_ID END)=ND.TargetId) 
	 OR ND.TargetId IS NULL)

	order by PublishDate
	
END
GO
EXEC SP_GET_NOTIFICATION_BY_EMP_ID