//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_group
    {
        public auth_group()
        {
            this.auth_group_permissions = new HashSet<auth_group_permissions>();
            this.auth_user_groups = new HashSet<auth_user_groups>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int company_id { get; set; }
    
        public virtual ICollection<auth_group_permissions> auth_group_permissions { get; set; }
        public virtual ICollection<auth_user_groups> auth_user_groups { get; set; }
    }
}
