//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_message
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string message { get; set; }
    
        public virtual auth_user auth_user { get; set; }
    }
}
