//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class auth_user
    {
        public auth_user()
        {
            this.auth_message = new HashSet<auth_message>();
            this.iclock_adminlog = new HashSet<iclock_adminlog>();
            this.devcmds = new HashSet<devcmds>();
            this.iclock_deptadmin = new HashSet<iclock_deptadmin>();
            this.auth_user_groups = new HashSet<auth_user_groups>();
            this.django_admin_log = new HashSet<django_admin_log>();
            this.auth_user_user_permissions = new HashSet<auth_user_user_permissions>();
        }
        [Key]
        public int id { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public bool is_staff { get; set; }
        public bool is_active { get; set; }
        public bool is_superuser { get; set; }
        public System.DateTime last_login { get; set; }
        public System.DateTime date_joined { get; set; }
        public Nullable<System.DateTime> date_email { get; set; }
        public Nullable<int> priv_id { get; set; }
        public Nullable<int> company_id { get; set; }

        public virtual ICollection<auth_message> auth_message { get; set; }
        public virtual company company { get; set; }
        public virtual user_priv user_priv { get; set; }
        public virtual ICollection<iclock_adminlog> iclock_adminlog { get; set; }
        public virtual ICollection<devcmds> devcmds { get; set; }
        public virtual ICollection<iclock_deptadmin> iclock_deptadmin { get; set; }
        public virtual ICollection<auth_user_groups> auth_user_groups { get; set; }
        public virtual ICollection<django_admin_log> django_admin_log { get; set; }
        public virtual ICollection<auth_user_user_permissions> auth_user_user_permissions { get; set; }
    }
}
