//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkinout
    {
        public int id { get; set; }
        public int userid { get; set; }
        public System.DateTime checktime { get; set; }
        public string checktype { get; set; }
        public int verifycode { get; set; }
        public string SN { get; set; }
        public string sensorid { get; set; }
        public string WorkCode { get; set; }
        public string Reserved { get; set; }
        public int company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual iclock iclock { get; set; }
        public virtual userinfo userinfo { get; set; }
    }
}
