//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("company")]
    public partial class company
    {
        public company()
        {
            this.auth_user = new HashSet<auth_user>();
            this.checkinout = new HashSet<checkinout>();
            this.iclock_adminlog = new HashSet<iclock_adminlog>();
            this.iclock_syncq = new HashSet<iclock_syncq>();
            this.departments = new HashSet<departments>();
            this.iclock_client = new HashSet<iclock_client>();
            this.iclock = new HashSet<iclock>();
            this.iclock_oplog = new HashSet<iclock_oplog>();
            this.devcmds = new HashSet<devcmds>();
            this.userinfo = new HashSet<userinfo>();
            this.devlog = new HashSet<devlog>();
        }
        [Key]
        public int companyid { get; set; }
        public string companyname { get; set; }

        public virtual ICollection<auth_user> auth_user { get; set; }
        public virtual ICollection<checkinout> checkinout { get; set; }
        public virtual ICollection<iclock_adminlog> iclock_adminlog { get; set; }
        public virtual ICollection<iclock_syncq> iclock_syncq { get; set; }
        public virtual ICollection<departments> departments { get; set; }
        public virtual ICollection<iclock_client> iclock_client { get; set; }
        public virtual ICollection<iclock> iclock { get; set; }
        public virtual ICollection<iclock_oplog> iclock_oplog { get; set; }
        public virtual ICollection<devcmds> devcmds { get; set; }
        public virtual ICollection<userinfo> userinfo { get; set; }
        public virtual ICollection<devlog> devlog { get; set; }
    }
}
