//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("departments")]
    public partial class departments
    {
        public departments()
        {
            this.userinfo = new HashSet<userinfo>();
            this.iclock_deptadmin = new HashSet<iclock_deptadmin>();
            this.iclock_messages = new HashSet<iclock_messages>();
            this.iclock = new HashSet<iclock>();
        }
        [Column(Order=0),Key]
        public int DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> supdeptid { get; set; }
        public int company_id { get; set; }
        public int SyncTag { get; set; }
        public string middleUpk_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<userinfo> userinfo { get; set; }
        public virtual ICollection<iclock_deptadmin> iclock_deptadmin { get; set; }
        public virtual ICollection<iclock_messages> iclock_messages { get; set; }
        public virtual ICollection<iclock> iclock { get; set; }
        public virtual iclock_client iclock_client { get; set; }
    }
}
