//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class devcmds
    {
        public int id { get; set; }
        public string SN_id { get; set; }
        public string CmdContent { get; set; }
        public System.DateTime CmdCommitTime { get; set; }
        public Nullable<System.DateTime> CmdTransTime { get; set; }
        public Nullable<System.DateTime> CmdOverTime { get; set; }
        public Nullable<int> CmdReturn { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
        public virtual company company { get; set; }
        public virtual iclock iclock { get; set; }
    }
}
