//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("devlog")]
    public partial class devlog
    {
        public int id { get; set; }
        public string SN_id { get; set; }
        public string OP { get; set; }
        public string Object { get; set; }
        public int Cnt { get; set; }
        public int ECnt { get; set; }
        public System.DateTime OpTime { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual iclock iclock { get; set; }
    }
}
