//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_adminlog
    {
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> User_id { get; set; }
        public string model { get; set; }
        public string action { get; set; }
        public string @object { get; set; }
        public int count { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
        public virtual company company { get; set; }
    }
}
