//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("iclock")]
    public partial class iclock
    {
        public iclock()
        {
            this.checkinout = new HashSet<checkinout>();
            this.devcmds = new HashSet<devcmds>();
            this.devlog = new HashSet<devlog>();
            this.iclock_iclockmsg = new HashSet<iclock_iclockmsg>();
            this.template = new HashSet<template>();
            this.iclock_oplog = new HashSet<iclock_oplog>();
            this.userinfo = new HashSet<userinfo>();
            this.userlist = new HashSet<userlist>();
        }
        [Key]
        public string SN { get; set; }
        public int State { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public string TransTimes { get; set; }
        public int TransInterval { get; set; }
        public string LogStamp { get; set; }
        public string OpLogStamp { get; set; }
        public string PhotoStamp { get; set; }
        public string Alias { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string UpdateDB { get; set; }
        public string Style { get; set; }
        public string FWVersion { get; set; }
        public Nullable<int> FPCount { get; set; }
        public Nullable<int> TransactionCount { get; set; }
        public Nullable<int> UserCount { get; set; }
        public string MainTime { get; set; }
        public Nullable<int> MaxFingerCount { get; set; }
        public Nullable<int> MaxAttLogCount { get; set; }
        public string DeviceName { get; set; }
        public string AlgVer { get; set; }
        public string FlashSize { get; set; }
        public string FreeFlashSize { get; set; }
        public string Language { get; set; }
        public string VOLUME { get; set; }
        public string DtFmt { get; set; }
        public string IPAddress { get; set; }
        public string IsTFT { get; set; }
        public string Platform { get; set; }
        public string Brightness { get; set; }
        public string BackupDev { get; set; }
        public string OEMVendor { get; set; }
        public string City { get; set; }
        public int AccFun { get; set; }
        public int TZAdj { get; set; }
        public int DelTag { get; set; }
        public string FPVersion { get; set; }
        public string PushVersion { get; set; }
        public int SyncTag { get; set; }
        public string middleUpk_id { get; set; }
    
        public virtual ICollection<checkinout> checkinout { get; set; }
        public virtual company company { get; set; }
        public virtual departments departments { get; set; }
        public virtual ICollection<devcmds> devcmds { get; set; }
        public virtual ICollection<devlog> devlog { get; set; }
        public virtual iclock_client iclock_client { get; set; }
        public virtual ICollection<iclock_iclockmsg> iclock_iclockmsg { get; set; }
        public virtual ICollection<template> template { get; set; }
        public virtual ICollection<iclock_oplog> iclock_oplog { get; set; }
        public virtual ICollection<userinfo> userinfo { get; set; }
        public virtual ICollection<userlist> userlist { get; set; }
    }
}
