//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class iclock_client
    {
        public iclock_client()
        {
            this.departments = new HashSet<departments>();
            this.iclock = new HashSet<iclock>();
            this.template = new HashSet<template>();
            this.userinfo = new HashSet<userinfo>();
            this.iclock_syncq = new HashSet<iclock_syncq>();
        }
        [Key]
        public string upk { get; set; }
        public string alias { get; set; }
        public Nullable<int> company_id { get; set; }
        public string cmdID { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<departments> departments { get; set; }
        public virtual ICollection<iclock> iclock { get; set; }
        public virtual ICollection<template> template { get; set; }
        public virtual ICollection<userinfo> userinfo { get; set; }
        public virtual ICollection<iclock_syncq> iclock_syncq { get; set; }
    }
}
