//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_license
    {
        public int id { get; set; }
        public string key { get; set; }
        public string UPK { get; set; }
        public int dl { get; set; }
        public int el { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string license { get; set; }
    }
}
