//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_oplog
    {
        public int id { get; set; }
        public string SN { get; set; }
        public int admin { get; set; }
        public int OP { get; set; }
        public System.DateTime OPTime { get; set; }
        public Nullable<int> Object { get; set; }
        public Nullable<int> Param1 { get; set; }
        public Nullable<int> Param2 { get; set; }
        public Nullable<int> Param3 { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual iclock iclock { get; set; }
    }
}
