//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class template
    {
        public int templateid { get; set; }
        public int userid { get; set; }
        public string Template1 { get; set; }
        public int FingerID { get; set; }
        public int Valid { get; set; }
        public int DelTag { get; set; }
        public string SN { get; set; }
        public Nullable<System.DateTime> UTime { get; set; }
        public string BITMAPPICTURE { get; set; }
        public string BITMAPPICTURE2 { get; set; }
        public string BITMAPPICTURE3 { get; set; }
        public string BITMAPPICTURE4 { get; set; }
        public Nullable<int> USETYPE { get; set; }
        public string Template2 { get; set; }
        public string Template3 { get; set; }
        public int SyncTag { get; set; }
        public string middleUpk_id { get; set; }
    
        public virtual iclock iclock { get; set; }
        public virtual iclock_client iclock_client { get; set; }
        public virtual userinfo userinfo { get; set; }
    }
}
