//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int id { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public bool is_staff { get; set; }
        public bool is_active { get; set; }
        public bool is_superuser { get; set; }
        public System.DateTime last_login { get; set; }
        public System.DateTime date_joined { get; set; }
        public Nullable<System.DateTime> date_email { get; set; }
        public Nullable<int> priv_id { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
