//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class userinfo
    {
        public userinfo()
        {
            this.checkinout = new HashSet<checkinout>();
            this.template = new HashSet<template>();
            this.userlist = new HashSet<userlist>();
        }
        [Key]
        public int userid { get; set; }
        public string badgenumber { get; set; }
        public int company_id { get; set; }
        public Nullable<int> defaultdeptid { get; set; }
        public string name { get; set; }
        public string Password { get; set; }
        public string Card { get; set; }
        public Nullable<int> Privilege { get; set; }
        public Nullable<int> AccGroup { get; set; }
        public string TimeZones { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string street { get; set; }
        public string zip { get; set; }
        public string ophone { get; set; }
        public string FPHONE { get; set; }
        public string pager { get; set; }
        public string minzu { get; set; }
        public string title { get; set; }
        public string SN { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> UTime { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<int> SECURITYFLAGS { get; set; }
        public int DelTag { get; set; }
        public int SyncTag { get; set; }
        public Nullable<int> RegisterOT { get; set; }
        public string middleUpk_id { get; set; }
        public Nullable<int> AutoSchPlan { get; set; }
        public Nullable<int> MinAutoSchInterval { get; set; }
        public Nullable<int> Image_id { get; set; }
    
        public virtual ICollection<checkinout> checkinout { get; set; }
        public virtual company company { get; set; }
        public virtual departments departments { get; set; }
        public virtual iclock iclock { get; set; }
        public virtual iclock_client iclock_client { get; set; }
        public virtual ICollection<template> template { get; set; }
        public virtual ICollection<userlist> userlist { get; set; }
    }
}
