//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTech.Demo.WdmsData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.Entity.ModelConfiguration.Conventions;
    
    public partial class WdmsEntities : DbContext
    {
        public WdmsEntities()
            : base("name=Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    
        public virtual DbSet<auth_group> auth_group { get; set; }
        public virtual DbSet<auth_group_permissions> auth_group_permissions { get; set; }
        public virtual DbSet<auth_message> auth_message { get; set; }
        public virtual DbSet<auth_permission> auth_permission { get; set; }
        public virtual DbSet<auth_user> auth_user { get; set; }
        public virtual DbSet<auth_user_groups> auth_user_groups { get; set; }
        public virtual DbSet<auth_user_user_permissions> auth_user_user_permissions { get; set; }
        public virtual DbSet<checkinout> checkinout { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<devcmds> devcmds { get; set; }
        public virtual DbSet<devlog> devlog { get; set; }
        public virtual DbSet<django_admin_log> django_admin_log { get; set; }
        public virtual DbSet<django_content_type> django_content_type { get; set; }
        public virtual DbSet<django_session> django_session { get; set; }
        public virtual DbSet<iclock> iclock { get; set; }
        public virtual DbSet<iclock_adminlog> iclock_adminlog { get; set; }
        public virtual DbSet<iclock_client> iclock_client { get; set; }
        public virtual DbSet<iclock_deptadmin> iclock_deptadmin { get; set; }
        public virtual DbSet<iclock_iclockmsg> iclock_iclockmsg { get; set; }
        public virtual DbSet<iclock_license> iclock_license { get; set; }
        public virtual DbSet<iclock_messages> iclock_messages { get; set; }
        public virtual DbSet<iclock_oplog> iclock_oplog { get; set; }
        public virtual DbSet<iclock_syncq> iclock_syncq { get; set; }
        //public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<template> template { get; set; }
        public virtual DbSet<user_priv> user_priv { get; set; }
        public virtual DbSet<userinfo> userinfo { get; set; }
        public virtual DbSet<userlist> userlist { get; set; }
        public virtual DbSet<test> test { get; set; }
    
       
    }
}
